resources:
- manager.yaml
images:
- name: controller
  newName: harbor.133.186.218.188.nip.io/suslmk-repository/kebe-controller01
  newTag: latest
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
